server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: eriknisler
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true