version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local-postgres-docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  postgres_network:
    driver: bridge